const button=document.querySelector('.menu-button'),nav=document.querySelector('.nav');button.addEventListener('click',()=>{const open=nav.classList.toggle('open');button.setAttribute('aria-expanded',open)});
    const revealSignup=(panel,input)=>requestAnimationFrame(()=>{panel.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>input.focus({preventScroll:true}),450)});
    const signupToggle=document.querySelector('#signup-toggle'),signup=document.querySelector('#uppsala-signup');signupToggle.addEventListener('click',()=>{const open=signup.classList.toggle('open');signupToggle.setAttribute('aria-expanded',open);signupToggle.textContent=open?'Close registration':'Register here';if(open)revealSignup(signup,document.querySelector('#signup-name'))});
    const uppsalaForm=document.querySelector('#uppsala-form'),signupStatus=document.querySelector('#signup-status');uppsalaForm.addEventListener('submit',async event=>{event.preventDefault();const submit=uppsalaForm.querySelector('.signup-submit');submit.disabled=true;submit.textContent='Sending…';signupStatus.className='signup-status';try{const response=await fetch(uppsalaForm.action,{method:'POST',body:new FormData(uppsalaForm),headers:{Accept:'application/json'}});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'The registration could not be completed.');uppsalaForm.reset();uppsalaForm.hidden=true;signupStatus.textContent='Thank you for registering. We will send practical information before the event.';signupStatus.className='signup-status show'}catch(error){signupStatus.textContent='Something went wrong. Check your details and try again, or use the email link.';signupStatus.className='signup-status show error';submit.disabled=false;submit.textContent='Send registration'}});
    const costaToggle=document.querySelector('#costa-toggle'),costaSignup=document.querySelector('#costa-signup');costaToggle.addEventListener('click',()=>{const open=costaSignup.classList.toggle('open');costaToggle.setAttribute('aria-expanded',open);costaToggle.textContent=open?'Close form':'Request a personal invitation';if(open)revealSignup(costaSignup,document.querySelector('#costa-name'))});
    const costaForm=document.querySelector('#costa-form'),costaStatus=document.querySelector('#costa-status');costaForm.addEventListener('submit',async event=>{event.preventDefault();const submit=costaForm.querySelector('.signup-submit');submit.disabled=true;submit.textContent='Sending…';costaStatus.className='signup-status';try{const response=await fetch(costaForm.action,{method:'POST',body:new FormData(costaForm),headers:{Accept:'application/json'}});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'The enquiry could not be submitted.');costaForm.reset();costaForm.hidden=true;costaStatus.textContent='Thank you for your interest. Henrik Hallenborg will contact you to discuss a personal arrangement and a suitable time.';costaStatus.className='signup-status show'}catch(error){costaStatus.textContent='Something went wrong. Check your details and try again, or use the email link.';costaStatus.className='signup-status show error';submit.disabled=false;submit.textContent='Send enquiry'}});
    const investorVideo=document.querySelector('#investor-video'),videoPlay=document.querySelector('#video-play');let videoPlayTracked=false;videoPlay.addEventListener('click',()=>investorVideo.play());investorVideo.addEventListener('play',()=>{videoPlay.classList.add('hidden');if(!videoPlayTracked&&typeof gtag==='function'){gtag('event','investerarmote_play',{video_title:'Investor meeting No. 1',video_file:'Investerarmote_Nr1.mp4'});videoPlayTracked=true}});investorVideo.addEventListener('pause',()=>{if(investorVideo.currentTime===0)videoPlay.classList.remove('hidden')});
    const letterToggle=document.querySelector('#letter-toggle'),letterSignup=document.querySelector('#letter-signup');letterToggle.addEventListener('click',()=>{const open=letterSignup.classList.toggle('open');letterToggle.setAttribute('aria-expanded',open);letterToggle.textContent=open?'Close form':'Yes, send me the investor letter';if(open)document.querySelector('#letter-name').focus()});
    const letterForm=document.querySelector('#letter-form'),letterStatus=document.querySelector('#letter-status');letterForm.addEventListener('submit',async event=>{event.preventDefault();const submit=letterForm.querySelector('.signup-submit');submit.disabled=true;submit.textContent='Registering…';letterStatus.className='signup-status';try{const response=await fetch(letterForm.action,{method:'POST',body:new FormData(letterForm),headers:{Accept:'application/json'}});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'The registration could not be completed.');letterForm.reset();letterForm.hidden=true;letterStatus.textContent='Thank you! You are now registered for forthcoming investor letters.';letterStatus.className='signup-status show'}catch(error){letterStatus.textContent='Something went wrong. Check your details and try again.';letterStatus.className='signup-status show error';submit.disabled=false;submit.textContent='Register me'}});

    document.querySelectorAll("[data-meeting]").forEach(trigger=>trigger.addEventListener("click",()=>{const city=trigger.dataset.meeting;document.querySelector("#meeting-location").value=city;const message=document.querySelector("#costa-message");message.value=city+" — "+message.value.replace(/^(Costa del Sol|Torrevieja|London|Londres) — /,"");if(!costaSignup.classList.contains("open"))costaToggle.click();else revealSignup(costaSignup,document.querySelector("#costa-name"));}));
    costaToggle.addEventListener("click",event=>{if(event.isTrusted){document.querySelector("#meeting-location").value="Costa del Sol";const message=document.querySelector("#costa-message");message.value=message.value.replace(/^(Costa del Sol|Torrevieja|London|Londres) — /,"");}});
